name: build-win64

permissions:
  contents: write
  
#on:
#  release:
#    types:
#      - published

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    steps:
    
    - name: Setup llvm-msvc
      uses: NewWorldComingSoon/setup-llvm-msvc@main
      with:
          cache-path: $env:TEMP
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build
      run: |
        cmake -Bbuild -TLLVM-MSVC_v143 -DCMAKE_WIN64_DRIVER=1
        cmake --build build --config Release
    
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ github.sha }}
        path: |
          build/sys/Release
          build/lib/Release
    
    - name: Compress artifacts
      uses: vimtor/action-zip@26a249fb00d43ca98dad77a4b3838025fc226aa1 # v1.1
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        files: |
         build/sys/Release/*.*
         build/lib/Release/*.*
        dest: ${{ github.event.repository.name }}-${{ github.sha }}.zip

    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      with:
        prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, '-pre') }}
        files: ${{ github.event.repository.name }}-${{ github.sha }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
